name: Build docs to branch gh-pages
on:
  push:
    branches:
      - main
jobs:
  build:
    name: Build project
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install NPM dependencies
        run: npm install

      - name: Build project assets
        run: npm run build

      - name: Copy files to docs folder
        run: |
          cp -p dist/{main.min.js,docs.min.js,main.min.css} docs/

      - name: Upload artifact
        uses: actions/upload-artifact@master
        with:
          name: static-site
          path: docs/
          if-no-files-found: error
  deploy:
    # Add a dependency to the build job
    needs: build
    name: Deploy project
    runs-on: ubuntu-latest

    steps:
      - name: Deploy to GitHub Pages
        uses: JamesIves/github-pages-deploy-action@4.1.2
        with:
          branch: gh-pages
          folder: docs
