name: Build Web components
on:
  push:
    branches:
      - test-build
jobs:
  build-project:
    name: Build project
    runs-on: [self-hosted,rpi]
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Install NPM dependencies
        run: npm install
      - name: Build project assets
        run: npm run build
