name: Build Web components
on:
  push:
    branches:
      - test-build
jobs:
  build-project:
    name: Build project
    runs-on: unbuntu-latest
    steps:
      - name: Install NPM dependencies
        run: npm install
      - name: Build project assets
        run: npm run build
