name: Build Web components
on:
  push:
    branches:
      - main
jobs:
  build-project:
    name: Build project
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Install NPM dependencies
        run: npm install
      - name: Build project assets
        run: npm run build
      - name: Upload artifact
        uses: actions/upload-pages-artifact
      - name: Deploy to GitHub Pages
        uses: actions/deploy-pages
