name: Release Component
on:
  push:
    branches:
      - main

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install dependencies
        run: npm install

      - name: Build component
        run: npm run build

      - name: Upload artifact
        uses: actions/upload-artifact@v1
        with:
          name: source-build
          path: dist/
          if-no-files-found: error

      - name: Commit and push changes
        run: |
          git config user.name "fpt-tom-du"
          git config user.email "tudq3@fsoft.com.vn"
          git add .
          git commit -m "Update dist folder"
          git push origin main

      - name: Create release
        id: create_release
        uses: actions/create-release@v1.0.0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: v${{ steps.get_version.outputs.version }}
          release_name: Release ${{ steps.get_version.outputs.version }}
          body: |
            Release ${{ steps.get_version.outputs.version }}
          draft: false
          prerelease: false

      - name: Download the artifact
        uses: actions/download-artifact@v1
        with:
          name: my-artifact
          path: ./

      - name: Upload assets
        id: upload-assets
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: source-build.zip
          asset_name: source-build.zip
          asset_content_type: application/zip
