name: Release Component
on:
  push:
    branches:
      - main

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install dependencies
        run: npm install

      - name: Build component
        run: npm run build

      - name: Commit and push changes
        run: |
          git config user.name "fpt-tom-du"
          git config user.email "tudq3@fsoft.com.vn"
          git add .
          git commit -m "Update dist folder"
          git push origin main

      - name: Create release
        id: create_release
        uses: actions/create-release@v1.0.0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: v${{ steps.get_version.outputs.version }}
          release_name: Release ${{ steps.get_version.outputs.version }} 1
          body: |
            Release ${{ steps.get_version.outputs.version }}
          draft: false
          prerelease: false

      - name: Upload release assets
        uses: actions/upload-artifact@v2
        with:
          name: release
          path: dist/
          if-no-files-found: error
